config:
  broadcast_updates: true # should nodes send updates to each other
  update_routes: true # should node calculate routes based on what their neighbour has sent them
routes:
  1:
    - 1 - 0 self
  2:
    - 2 - 0 self
  3:
    - 3 - 0 self
  4:
    - 4 - 0 self
  5:
    - 5 - 0 self
neighbours:
  - 1 2 2
  - 1 3 1
  - 2 3 4
  - 2 4 5
  - 3 4 100
  - 3 5 8
  - 4 5 1
nodes:
  1:
    packets: []
  2:
    packets: []
  3:
    packets: []
  4:
    packets: []
  5:
    packets: []