[package]
name = "root"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
educe = "0.6.0"
log = "0.4.22"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
serde_with = "3.9.0"
