config:
  broadcast_routes: true # should nodes send updates to each other, since this version of the visualiser does not store routes for each node, this should be true
  broadcast_seqno: true # should nodes broadcast their saved seqno when another node requests for it?
  update_routes: true # should node calculate routes based on what their neighbour has sent them
neighbours:
  - 1 2 2
  - 1 3 1
  - 2 3 4
  - 2 4 5
  - 3 4 100
  - 3 5 8
  - 4 5 1